use_frameworks!

platform :ios, '10.0'

target 'JNetUtils_Example' do
#  pod 'JNetUtils', :path => '../'
  pod 'JNetUtils', :path => '../JNetUtils.podspec'

  target 'JNetUtils_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
